AnnChouCode/TeaTime-Gathering

assets/scss/utils/_variables.scss

modify WA _variables.scss

---

assets/scss/all.scss
assets/scss/base/_utility.scss
assets/scss/components/_btn-notification.scss
assets/scss/components/_search-bar.scss
assets/scss/layout/_nav.scss
layout/btn-account.ejs
layout/btn-notification.ejs
layout/footer.ejs
layout/nav.ejs
pages/index.html

1. modify notification button collapse
2. modify footer email href
3. test btn-account
4. modify input search bar focus border color

modify notification button collapse

---

assets/scss/pages/_index.scss
layout/navigation-menu.ejs
layout/noviceTeaching.ejs
pages/index.html

1.調整首頁架構，原先左右兩側 md 時隱藏，調整成 lg 時隱藏
2.noviceTeaching.ejs 加上首頁左側欄錨點用的 id

modify index.html、noviceTeaching.ejs

---

assets/scss/all.scss
assets/scss/components/_account-login.scss
assets/scss/components/_notification.scss
assets/scss/utils/_variables.scss
layout/footer.ejs
layout/nav.ejs
layout/notification.ejs

1. modify variable.scss：enable-rfs false
2. modify the order of utility.scss & utilities  imports
3. modify className writing order

modify variables.scss & all.scss

---

assets/scss/layout/_feedback.scss
layout/feedback.ejs

1. Modify evaluate and message spacing
2. Modify evaluate block remove floating cover problem

Fix : navigation menu cover evaluate problem

---

assets/scss/all.scss
assets/scss/base/_utility.scss
assets/scss/components/_account-login.scss
assets/scss/components/_btn-active.scss
assets/scss/components/_btn-hover.scss
assets/scss/components/_custom-button.scss
layout/nav.ejs
layout/noviceTeaching.ejs
pages/reset-password.html

1. modify noviceTeaching sidebar RWD detail
2. doc custom-button.scss & review interactive code
3. modify nav.ejs login js

modify RWD detail & button interactive code review

---

assets/scss/layout/_tea-calendar.scss
layout/tea-calendar.ejs

1. Add tours and voting change effect
2. Modify hover background variable

Update : calendar block change effect

---

layout/nav.ejs
layout/notification.ejs
main.js
pages/index.html
pages/reset-password.html
pages/store-order.html

1. modify navbar collpase 登入登出按鈕
2. delete 重複的 CDN 引入 & jscode

modify login effect & jscode

---

assets/scss/components/_account-login.scss
layout/nav.ejs
pages/reset-password.html

modify form-validated-effect

---

assets/scss/base/_utility.scss
assets/scss/pages/_store-order.scss
layout/banner.ejs
layout/store-order-feedback.ejs
layout/store-order-menu.ejs
pages/store-order.html

modify (store-order-feedback.ejs、store-order-menu.ejs、banner.ejs、_utility.scss、store-order.html)

新增菜單客製 modal

---

assets/scss/pages/_store-order.scss
layout/notification.ejs
layout/store-order-menu.ejs
pages/store-order.html

點餐頁菜單取消 hover
input checkbox、radio，客製樣式
點餐頁開團中，4 改 2
通知鈴鐺，調整樣式

notification.ejs、store-order、

---

layout/tea-calendar.ejs
pages/store-order.html

1. 首頁「午茶行事曆」卡片版型修改
2. 店家頁「開團中」卡片版型修改

modify tea-calendar layout

---

assets/scss/pages/_calendar.scss
pages/calendar.html
pages/createVoting.html

1. modify 月曆頁 head css import
2. fix 月曆頁- 投票功能即時渲染
3. modify 時間選擇器 flatpickr 資料抓取
4. test 頁面資料拋轉

modify calendar.html head import & fix voting render

---

assets/scss/base/_base.scss
assets/scss/base/_utility.scss
assets/scss/pages/_store-order.scss
layout/store-order-feedback.ejs
pages/store-order.html

建立揪團
1.py-13 修正 py-12，去掉 height 50、height 24
2.張雅琪 改 黃莉琳
3.開團完成 訂購成功 新增 modal
購物車
1.小計 - 選訂起來
_utility.scss
1.新增 textarea 取消預設樣式
寫評價
1.新增 modal

modify (store-order.html、_utility.scss、_base.scss)

---

assets/scss/all.scss
assets/scss/components/_pagination.scss
assets/scss/pages/_calendar.scss
pages/calendar.html
pages/createVoting.html

1. feat createVoting.html 店家篩選排序與頁碼功能
2. style _pagination.scss

feat createVoting.html 店家篩選排序與頁碼功能

---

assets/scss/components/_search-bar.scss
layout/nav.ejs
pages/createVoting.html
pages/findStore.html

1. feat createVoting.html 搜尋框 autocomplete 功能
2. modify createVoting.html 店家渲染功能加入「搜尋」與篩選排序同時進行
3. modify nav.ejs 摺疊選單內，通知按鈕顏色更改
4. modify findStore.html 刪除 autocomplete.css 引入

modify nav collapse 通知按鈕 css

---

pages/calendar.html

因以下函式內包含太多 function 動作，所以將其內容函式動作細分重構：
1. 重構 initModalVotingCard 投票 modal 資料，共拆分為：
1-1. initModalVotingCard 初始化投票 modal 店家選項
1-2. renderVotingModalInfo 渲染投票活動資訊
1-3. renderVotingCard 渲染投票 modal 店家選項資料
1-4. voteStore 投票動作判斷是否已投過此店家
1-5. updateVotingAPI 變更投票資料庫 API
2. 新增更多程式碼註解

refactor：函式 initModalVotingCard 動作拆解重構

---

assets/scss/pages/_memberSystem.scss
pages/memberInfo.html
pages/orderSystem.html
pages/overallSystem.html
pages/voteSystem.html

完成訂單管理頁面、個人資料

---

assets/js/layout/find-store.js
layout/find-store.ejs
layout/memberSystem.ejs
pages/findStore.html
pages/memberInfo.html
pages/orderSystem.html
pages/overallSystem.html
pages/voteSystem.html

2.後臺管理連結資料庫
3.後台連結到個別的店家頁
4.留言上傳
5.消費統計圖表

1.修正ANN提出的版型

---

assets/js/pages/storeOrder-menu.js

modify (storeOrder-menu.js)
